# SPDX-FileCopyrightText: 2021 Daniel Laidig <laidig@control.tu-berlin.de>
#
# SPDX-License-Identifier: MIT

name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}

      - name: Install package
        run: pip install ".[dev]"

      - name: Run reuse lint
        run: reuse lint

      # Unhandled SyntaxError in flake8 when parsing Cython code with Python 3.10. For now, this hack disables running
      # flake8 when the Python version is 3.10. (In any case, there is not much benefit in running flake8 checking on
      # multiple Python versions.)
      - name: Disable flake8 on Python 3.10
        run: sed -i "s/--flake8//" setup.cfg
        if:  matrix.python-version == '3.10'

      - name: Run pytest
        run: pytest --nomatlab
